routes:
    homepage:
        name: home
        path: /

    signup:
        name: signup
        path: /signup

    login:
        name: login
        path: /login

    logout:
        name: logout
        path: /logout

    view one post by its id:
        name: viewPost
        path: /post/:id

    view all posts:
        name: viewAllPosts
        path: /posts

    update one post by its id:
        name: editPost
        path: /edit/post/:id

    delete one post by its id:
        name: deletePost
        path: /delete/post/:id

    admin panel index:
        name: admin
        path: /admin

    create a post:
        name: createPost
        path: /create/post