routes:
    homepage:
        name: home
        path: /

    view one post by its id:
        name: viewPost
        path: /post/:id

    view all posts:
        name: viewAllPosts
        path: /posts