routes:
    homepage:
        name: home
        path: /

    signup:
        name: signup
        path: /signup

    login:
        name: login
        path: /login

    logout:
        name: logout
        path: /logout

    view one post by its id:
        name: viewPost
        path: /post/:id

    view all posts:
        name: viewAllPosts
        path: /posts

    admin panel index:
        name: admin
        path: /admin

    create a post:
        name: createPost
        path: /admin/create/post